### ISSUE TITLE
Unable to Export Security Roles

### ISSUE THREAD

**Issue by Cam8863** [Keyfactor/kfutil#24]
When attempting to export Security Roles Roles KFUtil will fail with a 401 unauthorized. Checking the API Logs it's due to the fact that when hitting /KeyfactorAPI/Status/Endpoints the utility is adding the KEYFACTOR_DOMAIN variable along with the KEYFACTOR_USERNAME variable.

This fails due to the fact that per #23 you need to enter the DOMAIN\Username for the KEYFACTOR_USERNAME variable resulting in DOMAIN.local\DOMAIN\Username in the IIS Logs

**Comment by spbsoluble** [comment]
This should be resolved in `v0.5.1`
